In [1]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
import random

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X.shape

(442, 10)

In [4]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
lr = LinearRegression()

In [6]:
lr.fit(x_train,y_train)

LinearRegression()

In [10]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [11]:
lr.intercept_

151.88331005254167

In [7]:
y_pred = lr.predict(x_test)

In [9]:
r2_score(y_test,y_pred)

0.4399338661568969

In [18]:
class BMGDRegressor:
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lrmgd = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,x_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(int(x_train.shape[0]/self.batch_size)):
                idx = random.sample(range(x_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lrmgd * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
                self.coef_ = self.coef_ - (self.lrmgd * coef_der)
                
        print(self.coef_,self.intercept_)
        
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_
            

In [19]:
bmgdr = BMGDRegressor(batch_size=int(x_train.shape[0]/50),learning_rate=0.01,epochs=50)

In [20]:
bmgdr.fit(x_train,y_train)

[  52.23163702  -70.73368133  344.02121731  241.180337     15.49751393
  -33.26567889 -173.83483705  125.52598787  325.80161856  126.57646159] 152.36582803073026


In [22]:
y_pred_new = bmgdr.predict(x_test)

In [23]:
r2_score(y_test,y_pred_new)

0.43441583106426895

In [24]:
from sklearn.linear_model import SGDRegressor

In [32]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.5)

In [33]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [34]:
sgd.coef_

array([   1.06323826, -177.85734093,  505.76408455,  333.3005842 ,
        -92.46506458, -146.04703709, -217.72953002,   85.46426411,
        468.72537574,   76.45829791])

In [35]:
sgd.intercept_

array([163.21917076])

In [30]:
y_pred_new2 = sgd.predict(x_test)

In [31]:
r2_score(y_test,y_pred_new2)

0.4214436505083732