In [1]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
import time

In [2]:
X,y = load_diabetes(return_X_y=True)

In [4]:
X.shape


(442, 10)

In [5]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [6]:
lr = LinearRegression()

In [7]:
lr.fit(x_train,y_train)

LinearRegression()

In [8]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [12]:
lr.intercept_

151.88331005254167

In [10]:
y_pred = lr.predict(x_test)

In [11]:
r2_score(y_test,y_pred)

0.4399338661568969

In [23]:
class SGDRegressor:
    def __init__(self,learning_rate=0.01,epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lrsgd = learning_rate
        self.epochs = epochs
        
    def fit(self,x_train,y_train):
           
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(x_train.shape[0]):
                idx = np.random.randint(0,x_train.shape[0])
                y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_
                intercept_derivative = -2 * (y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lrsgd * intercept_derivative)
                
                coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
                self.coef_ = self.coef_ - (self.lrsgd * coef_der)
                
        print(self.intercept_,self.coef_)
        
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_

In [26]:
sgd = SGDRegressor(learning_rate=0.01,epochs=50)

In [31]:
sgd.fit(x_train,y_train)

157.0262180845429 [  62.94327762  -57.59456575  353.49032622  249.68710418   15.72570413
  -31.73328607 -171.14142955  129.36299278  319.01192009  126.56251345]


In [33]:
y_pred_new = sgd.predict(x_test)

In [34]:
r2_score(y_test,y_pred_new)

0.42732080276536355

In [35]:
from sklearn.linear_model import SGDRegressor

In [36]:
lrs = SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.01)

In [37]:
lrs.fit(x_train,y_train)

SGDRegressor(learning_rate='constant', max_iter=100)

In [39]:
lrs.coef_

array([  59.22039937,  -50.71291287,  321.20333604,  230.01454702,
         26.41538688,  -13.57386278, -164.83768398,  129.46701939,
        293.85255422,  127.46692108])

In [40]:
lrs.intercept_

array([150.4028481])

In [41]:
y_pred_new2 = lrs.predict(x_test)

In [ ]:
r2_score(y_test,y_pred_new2)